collections:
  - name: ethereum/client-go
    version: v1.12.0
    source: https://docker.io
  - name: sigp/lighthouse
    version: v4.4.0
    source: https://docker.io
  - name: flashbots/mev-boost
    version: 1.5
    source: https://docker.io